include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Essential rules for good code quality
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    slash_for_doc_comments: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    directives_ordering: true
    file_names: true
    library_names: true
    package_names: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    type_annotate_public_apis: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    unnecessary_this: true
    use_build_context_synchronously: true
    use_function_type_syntax_for_parameters: true
    valid_regexps: true
    
    # Additional rules for better code quality
    avoid_web_libraries_in_flutter: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    empty_catches: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    null_check_on_nullable_type_parameter: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_final_in_for_each: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unnecessary_await_in_return: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unrelated_type_equality_checks: true
    use_if_null_to_convert_nulls_to_bools: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    void_checks: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "example/**"
    - "test/**"
  errors:
    invalid_annotation_target: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-casts: true
    strict-raw-types: true
